sudo: required
services:
  - docker

before_install:
  - docker build -t noa/docker-aws-react -f Dockerfile.dev .

script:
  - docker run noa/docker-aws-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-aws-react"
  env: "DockerAwsReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-423389302817"
  bucket_path: "docker-aws-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  